services:
  postgres:
    image: postgres:16

    container_name: student_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: student_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: student_api

    restart: always

    ports:
      - "5000:5000"

    depends_on:
      - postgres

    environment:
        DATABASE_URL: postgresql://postgres:123456@postgres:5432/student_db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: